{"@t":"2020-07-27T10:42:23.7151512Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-07-27T10:42:27.3603765Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-07-27T10:42:27.4789974Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-07-27T10:55:02.6286284Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-07-27T10:55:05.2757355Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-07-27T10:55:05.3755222Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-07-27T10:57:30.1356715Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-07-27T10:57:32.9204979Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-07-27T10:57:33.0776940Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-07-27T10:59:16.4912737Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-07-27T10:59:19.3394438Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-07-27T10:59:19.4675082Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-07-27T12:57:03.8206221Z","@mt":"Job DEFAULT.7b703c2f-2784-44cf-a3b9-02488e489cc7 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 2 - Connection was terminated)\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 40\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 18\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:c6fec477-2f25-4102-bb2b-689e66e82f35","Module":"UserAccess"}
{"@t":"2020-07-27T12:57:03.3572194Z","@mt":"Job DEFAULT.e91d5c7e-6760-4eca-a39e-90e986056719 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 2 - Connection was terminated)\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:cd5faff8-535a-4903-8ec1-f91475776630","Module":"UserAccess"}
{"@t":"2020-07-27T12:57:03.0673304Z","@mt":"Job DEFAULT.37bea456-d355-4d7a-afff-9a0e7efc1e0e threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 2 - Connection was terminated)\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 36\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:79071f3e-c7b7-4a56-b800-2a33f600d974","Module":"UserAccess"}
{"@t":"2020-07-27T12:57:31.4913808Z","@mt":"Job DEFAULT.e91d5c7e-6760-4eca-a39e-90e986056719 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)\n ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 28\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T12:57:31.5078238Z","@mt":"Job DEFAULT.7b703c2f-2784-44cf-a3b9-02488e489cc7 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)\n ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 32\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 18\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T12:57:31.5080215Z","@mt":"Job DEFAULT.37bea456-d355-4d7a-afff-9a0e7efc1e0e threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)\n ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 29\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T12:58:01.3343740Z","@mt":"Job DEFAULT.e91d5c7e-6760-4eca-a39e-90e986056719 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)\n ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 28\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T12:58:01.4527464Z","@mt":"Job DEFAULT.7b703c2f-2784-44cf-a3b9-02488e489cc7 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)\n ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 32\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 18\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T12:58:01.5451624Z","@mt":"Job DEFAULT.37bea456-d355-4d7a-afff-9a0e7efc1e0e threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)\n ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 29\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T12:58:31.4154189Z","@mt":"Job DEFAULT.7b703c2f-2784-44cf-a3b9-02488e489cc7 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)\n ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 32\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 18\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T12:58:31.4155536Z","@mt":"Job DEFAULT.e91d5c7e-6760-4eca-a39e-90e986056719 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)\n ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 28\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T12:58:31.4889392Z","@mt":"Job DEFAULT.37bea456-d355-4d7a-afff-9a0e7efc1e0e threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)\n ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 29\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T12:59:02.7300901Z","@mt":"Job DEFAULT.7b703c2f-2784-44cf-a3b9-02488e489cc7 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 32\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 18\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T14:38:59.4977112Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-07-27T14:39:03.3257335Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-07-27T14:39:03.5433197Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-07-27T15:15:14.6160715Z","@mt":"Job DEFAULT.58f46752-27f6-480e-a8c8-9917bfdcd924 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)\n ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 32\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 18\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T15:15:14.6700581Z","@mt":"Job DEFAULT.cf4717e8-16ab-48d1-b531-3663ac800cf9 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)\n ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 29\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T15:15:14.4699187Z","@mt":"Job DEFAULT.bb5b43a1-ac37-4fc6-a22d-7ef45a3d0ae6 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)\n ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known\n   at System.Net.Dns.InternalGetHostByName(String hostName)\n   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)\n   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)\n   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\n   at System.Data.SqlClient.SqlConnection.Open()\n   at Base.Infrastructure.SqlConnectionFactory.GetOpenConnection() in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Base\\Base.Infrastructure\\SqlConnectionFactory.cs:line 27\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 28\n   at UserAccess.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\UnitOfWorkCommandHandlerDecorator.cs:line 31\n   at UserAccess.Infrastructure.Configuration.Processing.LoggingCommandHandlerDecorator`1.Handle(T command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\LoggingCommandHandlerDecorator.cs:line 33\n   at UserAccess.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\n   at UserAccess.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\UserAccess\\UserAccess.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 22\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\nClientConnectionId:00000000-0000-0000-0000-000000000000","Module":"UserAccess"}
{"@t":"2020-07-27T16:10:43.0418568Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-07-27T16:10:46.0340818Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-07-27T16:10:46.1749252Z","@mt":"Quartz started.","Module":"UserAccess"}
{"@t":"2020-07-27T16:11:34.1830290Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-07-27T16:11:37.2424779Z","@mt":"Quartz starting...","Module":"UserAccess"}
{"@t":"2020-07-27T16:11:37.3647903Z","@mt":"Quartz started.","Module":"UserAccess"}
